proxy:
  image: nginx
  volumes:
    - /usr/local/git/docker_file/proxy-web/nginx/nginx.conf:/etc/nginx/nginx.conf
  ports: 
    - 8080:80
    - 8443:443
  links:
    - web1
    - web2
web1:
  image: nginx
  volumes:
    - /usr/local/git/docker_file/proxy-web/web1:/usr/share/nginx/html
web2:
  image: nginx
  volumes:
    - /usr/local/git/docker_file/proxy-web/web2:/usr/share/nginx/html
