version: '2'
services:
  zabbix-db:
    image: monitoringartist/zabbix-db-mariadb
    env_file:
      - docker/mariadb/env
    ports:
      - "3306:3306"
    volumes:
      - zabbix-db:/var/lib/mysql
  zabbix:
    image: monitoringartist/zabbix-2.4
    links:
      - zabbix-db:zabbix.db
    env_file:
      - docker/zabbix/env
    ports:
      - "80:80"
      - "10051:10051"
volumes:
  zabbix-db:
    driver: local
