version: '2'
services:
  lb:
    build: ./NGINX/
    ports:
      - 10080:10080
    volumes:
#     - ./NGINX/pound.cfg:/etc/pound.cfg
#     - ./NGINX/pound.conf:/etc/nginx/conf.d/default.conf
     - ./NGINX/default.conf:/etc/nginx/conf.d/default.conf
     - ./html:/usr/share/nginx/html
    links:
      - node
    tty: true
  node:
    build: ./NODE/
    ports:
      - 8080:8080
    volumes:
      - ./html:/tmp
    tty: true
