version: '2'
services:
  web1:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - /C/Users/keiji.uehata/git/docker_files/nginx_lb/html/web1:/usr/share/nginx/html
    command: /bin/bash -c "echo 'daemon off;' >> /etc/nginx/nginx.conf && nginx"
  web2:
    image: nginx
    ports:
      - "8081:80"
    volumes:
      - /C/Users/keiji.uehata/git/docker_files/nginx_lb/html/web2:/usr/share/nginx/html
    command: /bin/bash -c "echo 'daemon off;' >> /etc/nginx/nginx.conf && nginx"
  lb1:
    image: nginx
    volumes:
      - /C/Users/keiji.uehata/git/docker_files/nginx_lb/conf/lb:/etc/nginx/conf
    ports:
      - "8082:80"
    links:
      - web1:web1
      - web2:web2
    command: /bin/bash -c "cp -pf /etc/nginx/conf/nginx.conf /etc/nginx/nginx.conf; echo 'daemon off;' >> /etc/nginx/nginx.conf && nginx"
