version: '2.0'
 
services:
    nginx:
        image: nginx
        ports:
            - '8080:80'
            - '8443:8443'
        volumes:
            - ./nginx:/etc/nginx/conf.d
            - ./logs/nginx:/var/log/nginx
            - ./wordpress:/var/www/html
            - /usr/local/1mg/data/www/letsencrypt:/etc/letsencrypt
        links:
            - wordpress
        restart: always
    mysql:
        image: mysql:5.5
        ports:
            - '3306:3306'
        volumes:
            - ./db-data:/var/lib/mysql 
        environment:
            - MYSQL_ROOT_PASSWORD=pass
        restart: always
    wordpress:
#        image: wordpress:4.9-php7.1-fpm
        image: wordpress:4.9.8-php7.2-fpm-alpine
        ports:
            - '9000:9000'
        volumes:
            - ./wordpress:/var/www/html
        environment:
            WORDPRESS_DB_NAME: wpdb
            WORDPRESS_TABLE_PREFIX: wp_
            WORDPRESS_DB_HOST: mysql
            WORDPRESS_DB_PASSWORD: pass
        links:
            - mysql
        depends_on:
            - mysql
        restart: always
