FROM ubuntu:16.04

RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y python-sphinx make
RUN apt-get install -y pandoc
RUN apt-get install -y texlive-luatex texlive-lang-cjk lmodern texlive-xetex

